version: '3'

services:
  app:
    build: .
    container_name: log_gen
    command: python generate_logs.py
    volumes:
      -  .:/app
    working_dir: /app
    environment:
      - DEBUG=1
      - LOG_FILE_PATH="logs.txt"


