---

version: '3.4'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./site/wp-content:/var/www/html/wp-content
      - ./init/prep.sh:/usr/local/bin/prep.sh
    ports:
      - '80:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: $db_host
      WORDPRESS_DB_USER: $db_user
      WORDPRESS_DB_PASSWORD: $db_password
      WORDPRESS_TABLE_PREFIX: $db_table_prefix
      WORDPRESS_DEBUG: $wp_debug_mode
      DISABLED_PLUGINS: $wp_plugins_to_disable

  db:
    image: mysql:latest
    platform: linux/x86_64
    volumes:
      - ./database:/var/lib/mysql
      - ./backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz
      - ./init/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
    restart: always
    ports: 
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $db_root_password
      MYSQL_DATABASE: $db_name
      MYSQL_USER: $db_user
      MYSQL_PASSWORD: $db_password
      WORDPRESS_TABLE_PREFIX: $db_table_prefix
      PRODUCTION_URL: $production_url
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: $db_user
      PMA_PASSWORD: $db_password
    ports:
      - "8080:80"