version: "3" 
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: MyWordPressDB
      MYSQL_USER: MyWordPressUser
      MYSQL_PASSWORD: password
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      restart: always
      environment:
        PMA_HOST: db
        PMA_USER: MyWordPressUser
        PMA_PASSWORD: password
      ports:
        - "8080:80"
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MyWordPressUser
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: MyWordPressDB
    volumes:
      ["./:/var/www/html"]
volumes:
  mysql: {}
