name: Update data.json and Push Changes

on:
  push:
    branches:
      - main
    paths: 
      - 'README.md'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Update data
        run: |
          echo "Starting to update data.json"
          python3 ./helpers/create_table.py
          python3 ./helpers/get_contribution_guidelines.py
          echo "data.json updated successfully"

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add ./data/*
          git commit -m "updated data files with new content"
          git push origin main
